Max steps now a parameter
uestla/Simplex-Calculator pull request #7
Opened 2021-01-05 19:36 UTC by nivshah

Previously, the max steps the solver would take was a constant. This
allows the user of the library to determine if they want more or less
max steps when using the solver.

The problem I was using this library for required more than the default 16 steps to solve, so I thought this change may be helpful for others.

2021-01-06 09:15 UTC, uestla requested changes
Hello and thank you for your PR.
Please see my review and update the code so I can then merge it.

2021-01-06 09:15 UTC, uestla commented on Simplex/Solver.php
> +	private $max_steps = 16;
Please keep the camelCase naming (i. e. `$maxSteps`).

2021-01-06 09:15 UTC, uestla commented on Simplex/Solver.php
> +	/** @param int $maxSteps (optional) */
Please use multiline phpDoc for both arguments.

2021-01-06 09:15 UTC, uestla commented on Simplex/Solver.php
> +	function __construct(Task $task, int $maxSteps = null)
This library requires PHP from 5.3 which doesn't support scalar typehints, please remove it.

2021-01-06 09:15 UTC, uestla commented on Simplex/Solver.php
> +	function getMaxSteps()
This getter is IMO not necessary since the variable is instantiated and (eventually) filled in constructor.

2021-01-06 09:15 UTC, uestla commented on Simplex/Solver.php
> +			if (count($this->steps) > $this->getMaxSteps()) {
See above - here the class variable can be accessed directly.

2021-01-06 10:44 UTC, uestla commented on Simplex/Solver.php
> +		if ($maxSteps !== null) {
This condition wouldn't have to be here if the default argument value was `16` instead of `null`.
Also please add re-typing to `(int) $maxSteps`.

2021-01-06 15:09 UTC, nivshah commented
Will make these changes shortly, thanks for reviewing.

2021-01-08 16:53 UTC, uestla requested changes
Thank you for your changes, all looks great, just two final tiny changes according to coding standards.

Then I'll merge it.

2021-01-08 16:53 UTC, uestla commented on Simplex/Solver.php
> +	 *
Please remove this blank phpDoc line.

2021-01-08 16:53 UTC, uestla commented on Simplex/Solver.php
> + 	 * @param int $maxSteps
Please ad a space after `@param`, making it `@param  int $maxSteps`.

2021-01-08 16:56 UTC, nivshah commented
No problem, done.

2021-01-08 17:04 UTC, uestla approved these changes

2021-01-08 17:08 UTC, merged

2021-01-08 17:10 UTC, uestla commented
Tests pass, merging.
Thanks again! :-)

2021-01-08 17:10 UTC, nivshah commented
Awesome, thank you for your work on this library.